### PR TITLE
Add scientific notation when the result is too large

### PR DESCRIPTION
**Pull request by Aras14HD**
Since I saw somebody ask and mention that this bot is written in rust, I wanted to add the scientific notation in this case.

For some things I just guessed (how many digits to display, chose 300, and how to add it to the comment), so please tell me any improvements that should be made to merge, like the variable names.

Thanks for making and running this bot! :)

P.S.: Maybe add a license, so contributors aren't technically breaking copyright.

### CODE REVIEW

**Comment by tolik518** [comment]
Hey, thank you for your contribution. I'll take a look at it in the following days :)

**Comment by Aras14HD** [comment]
Yea made some mistakes, did it in a rush and too caught up making it even build in my env with nix (openssl issues), but I have now added the line to the tests (and improved formatting) and made clippy happy. Now the comment/line on scientific notation is:

In scientific notation they are [1.20e2, 7.20e2, 6.41233768827655218388409630305e10000] though :)

**Comment by tolik518** [comment]
Thanks for fixing up :)

One small nitpick before I take a closer look at it tomorrow: could you please move the number of digits (30) to a separate variable and also write a test for what happens for the highest possible number? There should be a constant for it (100_001)

**Comment by Aras14HD** [comment]
Of course. OpenSSL is not an issue with this project, it is more an issue with NixOS itself, as using it is not as straight forward as expected (you need a separate package installed).

I made the constant `pub(crate)`. And I just noticed a minor bug in my code, I am not rounding, will fix that.

**Comment by tolik518** [comment]
Rounding is not that important. Just open a ticket, describe the issue and link this PR to it, so the issue won't get lost

**Comment by Aras14HD** [comment]
Did it anyway, wasn't that hard, just had to carry over the 9s, now it works.

**Comment by tolik518** [comment]
I just looked over it, thank you very much for your contribution!
It would be nice if you could move the rounding part to its own function and write tests for that. Other than that you did good work and I'll accept the PR as soon as possible.

**Comment by tolik518** [comment]
Perfect! Thank you @Aras14HD!

**Pull request merged**
